### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by IgorDePaula** [radnan/rdn-upload#4]
I tryed your tutorial and i received this:
I do equals in view: <?php $this->uploads()->get($this->file)?> and on click...

Not Found

The requested URL /files\d\3\0\d300695b7592fe77480287cdf0db061b9d35a50c\Introduo.pdf was not found on this server.

**Comment by apoca** [comment]
Do you create the link to files?!

**Comment by IgorDePaula** [comment]
yes, like docs.

2015-03-09 19:14 GMT-03:00 Miguel Vieira <notifications@github.com>:

**Comment by Syberon** [comment]
In first, sorry for my english))

I also encountered this problem. It consists in the fact that the code to generate the sequence for the uploaded file using a constant DIRECTORY_SEPARATOR (RdnUpload\Container.php::generateSequence(...)). In this regard, if the site was developed and filled with content on Windows-machine and later moved to Linux-hosting, the sequences for uploaded files stored in database (or somewhere else) slill using windows path separator "\" and application don't work with message "The requested URL ... was not found on this server."

My solution of this problem is by overloading function generateSequence(...) in custom Container that extending original RdnUpload\Container.php, but...

But it would be better to add some option to config of original RdnUpload module to define preferred separator (may be set it to DIRECTORY_SEPARATOR by default, but windows works with both of them so it can be '/' by default what works on both OS)

I hope that my proposal will be realized in next version and the need to use of custom class will disappear:)

**Comment by radnan** [comment]
@IgorDePaula looks like there is a directory separator issue here. Could you please run a query on your stored file ids in your database to replace the back slash `\` with a forward slash `/` and see if that fixes the issue?

**Comment by radnan** [comment]
@Syberon thanks for the heads up on the path separator issue. I've fixed it and tagged a new release. Could you check that to see if it solves your problem?

**Comment by Syberon** [comment]
@radnan, thanks for fast response. Today i tested a new release and all works fine.
